#!/usr/bin/env python3
import _bw

#_bw.getrp('test.bw', 'test_tss.bed', 'out.tab', 10000.0, 0, 0)
#_bw.getrp('/data5/DC_results/Result_new3/dataset53709/53709_treat.bw', 'hg38.tss', 'out.tab', 10000.0, -1000, 1000)
_bw.getrp('/data5/DC_results/Result_new2/dataset59515/59515_treat.bw', 'hg38.tss', 'out2.tab', 10000.0, 0, 0)
#_bw.getrp('42359_treat.bw', 'hg38.tss', 'out.tab', 10000.0)
