#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

input=$1
chrom=$2
output=$3

macs2 pileup --extsize 147 -i $input -o ${input}.bdg
bedClip ${input}.bdg $chrom ${input}.bdg.tmp
bedGraphToBigWig ${input}.bdg.tmp $chrom ${output}
rm ${input}.bdg ${input}.bdg.tmp
